apiVersion: v1
kind: PersistentVolume
metadata:
  name: aiops-shared-logs
  labels:
    app.kubernetes.io/name: aiops-shared-logs
    app.kubernetes.io/part-of: aiops-lab
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: aiops-local
  hostPath:
    path: /var/local/aiops-lab/logs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-service-logs
  namespace: aiops-lab
  labels:
    app.kubernetes.io/name: demo-service-logs
    app.kubernetes.io/part-of: aiops-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aiops-local
  volumeName: aiops-shared-logs
  resources:
    requests:
      storage: 1Gi

